- type: job
  id: StationTrafficController
  name: job-name-stc
  description: job-description-stc
  playTimeTracker: JobStc
  startingGear: StcGear
  alwaysUseSpawner: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 27000 # triad
    - !type:RoleTimeRequirement
      role: JobSecurityGuard
      time: 1800 # triad
  canBeAntag: false
  icon: "JobIconStc"
  assignedCompany: Colonial
  supervisors: job-supervisors-sr
  weight: 160
  displayWeight: 50 # Second from the top
  setPreference: true
  access:
  - Service
  - Maintenance
  - External
  - Frontier
  - StationTrafficController
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: StcGear
  equipment:
    id: StcPDA
  storage:
    back:
    - Flash
    - RubberStampStc
    - EncryptionKeyStationMaster
    - PhoneInstrumentHigh
