- type: loadoutGroup
  id: DoIJumpsuit
  name: loadout-group-contractor-jumpsuit
  loadouts:
  - ChiefEngineerJumpsuit
  - ChiefEngineerJumpskirt
  - ChiefEngineerTurtleneck
  - ChiefEngineerTurtleneckSkirt
  - SeniorDoIJumpsuit
  - SeniorDoIJumpskirt
  fallbacks:
  - ChiefEngineerJumpsuit

- type: loadoutGroup
  id: DoINeck
  name: loadout-group-chief-engineer-neck
  minLimit: 0
  loadouts:
  - DoICloak
  - DoIMantle

- type: loadoutGroup
  id: DoIBackpack
  name: loadout-group-contractor-backpack
  loadouts:
  - PlantManagerMessengerBag
  fallbacks:
  - StationEngineerBackpack
  subgroups:
  - ContractorBackpack
