- type: loadoutGroup
  id: SectorTechnicianHead
  name: loadout-group-contractor-head
  minLimit: 0
  loadouts:
  - ClothingHeadHatBeretEngineering
  - ClothingHeadHatHardhatBlue
  - ClothingHeadHatHardhatOrange
  - ClothingHeadHatHardhatRed
  - ClothingHeadHatHardhatWhite
  - ClothingHeadHatHardhatYellow
  - ClothingHeadHatHardhatYellowDark

- type: loadoutGroup
  id: PlantBelt
  name: loadout-group-contractor-belt
  loadouts:
  - ContractorClothingBeltUtility
  - ContractorClothingBeltUtilityFilled
  - ContractorClothingBeltStorageWaistbag
  - ContractorClothingBeltSalvageWebbingFilledNF
  - ContractorBoxFolderClipboard
  fallbacks:
  - ContractorClothingBeltUtilityFilled

- type: loadoutGroup
  id: SectorTechnicianJumpsuit
  name: loadout-group-contractor-jumpsuit
  loadouts:
  - StationEngineerJumpsuit
  - StationEngineerJumpskirt
  - StationEngineerHazardsuit
  - AtmosphericTechnicianJumpsuit
  - AtmosphericTechnicianJumpskirt
  - AtmosphericTechnicianJumpsuitCasual
  fallbacks:
  - StationEngineerJumpsuit

- type: loadoutGroup
  id: SectorTechnicianBackpack
  name: loadout-group-contractor-backpack
  loadouts:
  - StationEngineerBackpack
  - StationEngineerSatchel
  - StationEngineerDuffel
  - AtmosphericTechnicianBackpack
  - AtmosphericTechnicianSatchel
  - AtmosphericTechnicianDuffel
  fallbacks:
  - StationEngineerBackpack
