- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic-nf
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # triad
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3600 # traid
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 54000 # triad
  startingGear: BrigmedicGear
  icon: JobIconBrigmedicNF
  supervisors: job-supervisors-bailiff
  weight: 125
  displayWeight: 35
  assignedCompany: TSF
  canBeAntag: false
  accessGroups:
  - GeneralNfsdBrigmedicAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
    - type: SurgerySpeedModifier
      SpeedModifier: 1.65
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: BrigmedicGear
  equipment:
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
  storage:
    back:
    - EncryptionKeyMedical
    - Magazine45_ACPPistolFMJ
    - BaseSecurityUplinkRadioOfficer #Mono: Changed to officer uplink
    - RadioHandheldNF # Mono
